gold_standard_grammar_facts = [
    "GrammatikVersion(4_1).",
    "GrammatikHatSupport(UnicodeSupport).",
    "GrammatikStartetMit(Formula).",
    "GrammatikDefiniertRegel(Formula).",
    "RegelBestehtAus(Formula, Expression, Punkt).",
    "GrammatikDefiniertRegel(Expression).",
    "RegelHatOption(Expression, QuantifiedFormula).",
    "RegelHatOption(Expression, Implication).",
    "GrammatikDefiniertRegel(Implication).",
    "RegelBestehtAus(Implication, Disjunction).",
    "RegelKannOptionalHaben(Implication, ImplicationOperator).",
    "GrammatikDefiniertRegel(Disjunction).",
    "RegelBestehtAus(Disjunction, Conjunction).",
    "RegelKannOptionalHaben(Disjunction, DisjunctionOperator).",
    "GrammatikDefiniertRegel(Conjunction).",
    "RegelBestehtAus(Conjunction, Negation).",
    "RegelKannOptionalHaben(Conjunction, ConjunctionOperator).",
    "GrammatikDefiniertRegel(Negation).",
    "RegelHatOption(Negation, MinusAtomExpression).",
    "RegelHatOption(Negation, AtomExpression).",
    "GrammatikDefiniertRegel(AtomExpression).",
    "RegelHatOption(AtomExpression, Atom).",
    "RegelHatOption(AtomExpression, ParenthesizedExpression).",
    "GrammatikDefiniertRegel(QuantifiedFormula).",
    "RegelBestehtAus(QuantifiedFormula, KeywordAll, Var, KlammerAuf, Expression, KlammerZu).",
    "GrammatikDefiniertRegel(Atom).",
    "RegelBestehtAus(Atom, Predicate).",
    "RegelKannOptionalHaben(Atom, ArgList).",
    "GrammatikDefiniertRegel(ArgList).",
    "RegelBestehtAus(ArgList, Term).",
    "RegelKannMehrereHaben(ArgList, Term, Komma).",
    "GrammatikDefiniertRegel(Term).",
    "RegelHatOption(Term, Predicate).",
    "RegelHatOption(Term, Var).",
    "GrammatikDefiniertToken(Predicate).",
    "TokenStartetMit(Predicate, GrossbuchstabeOderUmlaut).",
    "TokenEnthältZeichen(Predicate, BuchstabenZahlenUnterstrich).",
    "GrammatikDefiniertToken(Var).",
    "TokenStartetMit(Var, Kleinbuchstabe).",
    "TokenEnthältZeichen(Var, BuchstabenZahlenUnterstrich).",
    "GrammatikDefiniertOperator(Implies, '->').",
    "GrammatikDefiniertOperator(Or, '|').",
    "GrammatikDefiniertOperator(And, '&').",
    "GrammatikDefiniertOperator(Minus, '-').",
    "GrammatikDefiniertKeyword(All).",
    "GrammatikDefiniertSymbol(Punkt, '.').",
    "GrammatikDefiniertSymbol(KlammerAuf, '(').",
    "GrammatikDefiniertSymbol(KlammerZu, ')').",
    "GrammatikDefiniertSymbol(Komma, ',').",
    "GrammatikIgnoriert(Whitespace).",
    "GrammatikImportiert(CommonWhitespace)."
]